// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNoiTruSV.Data;

#nullable disable

namespace QuanLyNoiTruSV.Migrations
{
    [DbContext(typeof(QuanLyNoiTruSVContext))]
    partial class QuanLyNoiTruSVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNoiTruSV.Models.DonDangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DonDangKys");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.KhuNoiTru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenKhu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("KhuNoiTrus");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.PhanCongNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhuNoiTruId")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhuNoiTruId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("PhanCongNhanViens");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToaNhaId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ToaNhaId");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.ToaNha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhuNoiTruId")
                        .HasColumnType("int");

                    b.Property<string>("TenToa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhuNoiTruId");

                    b.ToTable("ToaNhas");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.DonDangKy", b =>
                {
                    b.HasOne("QuanLyNoiTruSV.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNoiTruSV.Models.SinhVien", "SinhVien")
                        .WithMany("DonDangKys")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyNoiTruSV.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.HopDong", b =>
                {
                    b.HasOne("QuanLyNoiTruSV.Models.Phong", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNoiTruSV.Models.SinhVien", "SinhVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.PhanCongNhanVien", b =>
                {
                    b.HasOne("QuanLyNoiTruSV.Models.KhuNoiTru", "KhuNoiTru")
                        .WithMany()
                        .HasForeignKey("KhuNoiTruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNoiTruSV.Models.NhanVien", "NhanVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuNoiTru");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.Phong", b =>
                {
                    b.HasOne("QuanLyNoiTruSV.Models.ToaNha", "ToaNha")
                        .WithMany("Phongs")
                        .HasForeignKey("ToaNhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.ToaNha", b =>
                {
                    b.HasOne("QuanLyNoiTruSV.Models.KhuNoiTru", "KhuNoiTru")
                        .WithMany("ToaNhas")
                        .HasForeignKey("KhuNoiTruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuNoiTru");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.HopDong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.KhuNoiTru", b =>
                {
                    b.Navigation("ToaNhas");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.NhanVien", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.Phong", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.SinhVien", b =>
                {
                    b.Navigation("DonDangKys");

                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QuanLyNoiTruSV.Models.ToaNha", b =>
                {
                    b.Navigation("Phongs");
                });
#pragma warning restore 612, 618
        }
    }
}
